import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ProductProvider } from "@/app/context/productContext";
import { CartProvider } from "@/app/context/cartContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <CartProvider>
            <Navigation />
            <main>{children}</main>
          </CartProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
