export const metadata = {
  title: "MV | Dashboard",
  description: "Generated by create next app",
};


export default function Layout({ children }) {
  return (
<div className="pt-8">
    {children}
</div>
  );
}
